// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthorizationFields: typeof import('./src/components/Login/AuthorizationFields.vue')['default']
    BaseBreadcrumbs: typeof import('./src/components/BaseBreadcrumbs.vue')['default']
    BaseForm: typeof import('./src/components/BaseForm.vue')['default']
    BaseHeader: typeof import('./src/components/Header/BaseHeader.vue')['default']
    BaseHeaderUser: typeof import('./src/components/Header/BaseHeaderUser.vue')['default']
    BaseLink: typeof import('./src/components/Link/BaseLink.vue')['default']
    BaseLoader: typeof import('./src/components/BaseLoader.vue')['default']
    BaseLocale: typeof import('./src/components/Header/BaseLocale.vue')['default']
    BasePreloader: typeof import('./src/components/BasePreloader.vue')['default']
    BaseSpinner: typeof import('./src/components/BaseSpinner.vue')['default']
    BaseTable: typeof import('./src/components/Table/BaseTable.vue')['default']
    BaseTableItem: typeof import('./src/components/Table/BaseTableItem.vue')['default']
    BaseTableRow: typeof import('./src/components/Table/BaseTableRow.vue')['default']
    BaseThemeSwitcher: typeof import('./src/components/Header/BaseThemeSwitcher.vue')['default']
    BaseToasts: typeof import('./src/components/Toast/BaseToasts.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LoginForm: typeof import('./src/components/Login/LoginForm.vue')['default']
    RegisterFields: typeof import('./src/components/Login/RegisterFields.vue')['default']
    RestorePasswordForm: typeof import('./src/components/Login/RestorePasswordForm.vue')['default']
    RewritableParagraph: typeof import('./src/components/RewritableParagraph.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
