// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthLinks: typeof import('./src/components/AuthLinks.vue')['default']
    BaseBreadcrumbs: typeof import('./src/components/BaseBreadcrumbs.vue')['default']
    BaseHeader: typeof import('./src/components/Header/BaseHeader.vue')['default']
    BaseLink: typeof import('./src/components/Link/BaseLink.vue')['default']
    BaseLocale: typeof import('./src/components/Header/BaseLocale.vue')['default']
    BaseTable: typeof import('./src/components/Table/BaseTable.vue')['default']
    BaseTableItem: typeof import('./src/components/Table/BaseTableItem.vue')['default']
    BaseTableRow: typeof import('./src/components/Table/BaseTableRow.vue')['default']
    BaseThemeSwitcher: typeof import('./src/components/Header/BaseThemeSwitcher.vue')['default']
    BaseToasts: typeof import('./src/components/Toast/BaseToasts.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RewritableParagraph: typeof import('./src/components/RewritableParagraph.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    ToastNotification: typeof import('./src/components/ToastNotification.vue')['default']
    ToastsContainer: typeof import('./src/components/ToastsContainer.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
