// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthLinks: typeof import('./src/components/AuthLinks.vue')['default']
    BaseHeader: typeof import('./src/components/Header/BaseHeader.vue')['default']
    BaseLink: typeof import('./src/components/Link/BaseLink.vue')['default']
    BaseLocale: typeof import('./src/components/Header/BaseLocale.vue')['default']
    BaseTable: typeof import('./src/components/Table/BaseTable.vue')['default']
    BaseTableItem: typeof import('./src/components/Table/BaseTableItem.vue')['default']
    BaseTableRow: typeof import('./src/components/Table/BaseTableRow.vue')['default']
    BaseThemeSwitcher: typeof import('./src/components/Header/BaseThemeSwitcher.vue')['default']
    BoardHeader: typeof import('./src/components/board/BoardHeader.vue')['default']
    BoardSectionItem: typeof import('./src/components/board/BoardSectionItem.vue')['default']
    BoardSectionsList: typeof import('./src/components/board/BoardSectionsList.vue')['default']
    BoardSettings: typeof import('./src/components/board/BoardSettings.vue')['default']
    BoardTaskItem: typeof import('./src/components/board/BoardTaskItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RewritableParagraph: typeof import('./src/components/RewritableParagraph.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    TagBadge: typeof import('./src/components/TagBadge.vue')['default']
    TagList: typeof import('./src/components/TagList.vue')['default']
    ToastNotification: typeof import('./src/components/ToastNotification.vue')['default']
    ToastsContainer: typeof import('./src/components/ToastsContainer.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
