// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseForm: typeof import('./src/components/BaseForm.vue')['default']
    BaseHeader: typeof import('./src/components/BaseHeader.vue')['default']
    BaseHeaderUser: typeof import('./src/components/BaseHeaderUser.vue')['default']
    BaseLink: typeof import('./src/components/Link/BaseLink.vue')['default']
    BaseRewritableParagraph: typeof import('./src/components/BaseRewritableParagraph.vue')['default']
    BaseSortableTable: typeof import('./src/components/SortableTable/BaseSortableTable.vue')['default']
    BaseSortableTableItem: typeof import('./src/components/SortableTable/BaseSortableTableItem.vue')['default']
    BaseSortableTableRow: typeof import('./src/components/SortableTable/BaseSortableTableRow.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
